const testData = [
  {
    id: 1,
    country: "lorem country",
    name: "Minsk",
    localization: "BY",
    rate: 0.3,
    status: false,
    hours: 199,
    lorem: 1,
    clients: 2114,
    total: 2345,
  },
  {
    id: 2,
    country: "lorem country",
    name: "London",
    localization: "ENG",
    rate: 0.5,
    status: false,
    hours: 14,
    lorem: 2,
    clients: 19,
    total: 114,
  },
  {
    id: 3,
    country: "lorem country",
    name: "Paris",
    localization: "FR",
    rate: 3.4,
    status: true,
    hours: 768,
    lorem: "No",
    clients: 7832,
    total: 56.7887,
  },
  {
    id: 4,
    country: "lorem country",
    name: "Kiev",
    localization: "UA",
    rate: 0.1,
    status: true,
    hours: 786,
    lorem: 1,
    clients: 345,
    total: 987.65,
  },
  {
    id: 5,
    country: "lorem country",
    name: "Moscow",
    localization: "RU",
    rate: 0.4,
    status: false,
    hours: 1879,
    lorem: true,
    clients: 21614,
    total: 26345,
  },
  {
    id: 6,
    country: "lorem country",
    name: "Riga",
    localization: "PL",
    rate: 0.9,
    status: true,
    hours: 1949,
    lorem: "lorem lorem lorem lorem",
    clients: 27114,
    total: 23495,
  },
  {
    id: 7,
    country: "lorem country",
    name: "Saint-Petersburg",
    localization: "RU",
    rate: 0.1,
    status: false,
    hours: 159,
    lorem: "lorem lorem lorem lorem",
    clients: 24,
    total: 2,
  },
  {
    id: 8,
    country: "lorem country",
    name: "Rostov",
    localization: "RU",
    rate: 0.3,
    status: false,
    hours: 199,
    lorem: "lorem lorem lorem lorem",
    clients: 2114,
    total: 2345,
  },
  {
    id: 9,
    country: "lorem country",
    name: "Vladimir",
    localization: "RU",
    rate: 0.6,
    status: true,
    hours: 134,
    lorem: "lorem lorem lorem lorem",
    clients: 614,
    total: 285,
  },
  {
    id: 10,
    country: "lorem country",
    name: "Grodno",
    localization: "BY",
    rate: 0.1,
    status: false,
    hours: 0,
    lorem: "lorem ",
    clients: 1,
    total: 1,
  },
];

export default testData;
